### ISSUE TITLE
Web: Missing GL.recordError function

### ISSUE THREAD

**Issue by koalefant** [not-fl3/miniquad#129]
Occasionally I am getting reports of missing GL.recordError function:
```
Callstack: TypeError: GL.recordError is not a function
     at _glGenObject (https://cratebeforeattack.com/play/gl.js:248:16)
     at glGenTextures (https://cratebeforeattack.com/play/gl.js:619:13)
```

**Comment by koalefant** [comment]
Not confirmed yet, but I suspect that this is caused by loss of WebGL context: https://www.khronos.org/webgl/wiki/HandlingContextLost
