### ISSUE TITLE
android binaries act as if they work on android 8, but use android 9 java fields

### ISSUE THREAD

**Issue by oli-obk** [not-fl3/miniquad#488]
To make sure it's not an issue of my setup, I installed the zemeroth game from the appstore. It install fine without any version requirements or other complaints. It then starts and immediately crashes with 

```
09-25 14:17:57.931 20901 20901 E AndroidRuntime: Process: rust.zemeroth, PID: 20901
09-25 14:17:57.931 20901 20901 E AndroidRuntime: java.lang.NoSuchFieldError: No field layoutInDisplayCutoutMode of type I in class Landroid/view/WindowManager$LayoutParams; or its superclasses (declaration of 'android.view.WindowManager$LayoutParams' appears in /system/framework/framework.jar:classes2.dex)
09-25 14:17:57.931 20901 20901 E AndroidRuntime: 	at rust.zemeroth.MainActivity$1.run(MainActivity.java:290)
09-25 14:17:57.931 20901 20901 E AndroidRuntime: 	at android.app.Activity.runOnUiThread(Activity.java:6152)
09-25 14:17:57.931 20901 20901 E AndroidRuntime: 	at rust.zemeroth.MainActivity.setFullScreen(MainActivity.java:283)
09-25 14:17:57.931 20901 20901 E AndroidRuntime: 	at quad_native.QuadNative.activityOnCreate(Native Method)
09-25 14:17:57.931 20901 20901 E AndroidRuntime: 	at rust.zemeroth.MainActivity.onCreate(MainActivity.java:235)
09-25 14:17:57.931 20901 20901 E AndroidRuntime: 	at android.app.Activity.performCreate(Activity.java:6975)
09-25 14:17:57.931 20901 20901 E AndroidRuntime: 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1213)
09-25 14:17:57.931 20901 20901 E AndroidRuntime: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2858)
09-25 14:17:57.931 20901 20901 E AndroidRuntime: 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2983)
09-25 14:17:57.931 20901 20901 E AndroidRuntime: 	at android.app.ActivityThread.-wrap11(Unknown Source:0)
09-25 14:17:57.931 20901 20901 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1668)
09-25 14:17:57.931 20901 20901 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:108)
09-25 14:17:57.931 20901 20901 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:206)
09-25 14:17:57.931 20901 20901 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6760)
09-25 14:17:57.931 20901 20901 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
09-25 14:17:57.931 20901 20901 E AndroidRuntime: 	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
09-25 14:17:57.931 20901 20901 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:845)
09-25 14:17:57.935  2388  5559 W ActivityManager:   Force finishing activity rust.zemeroth/.MainActivity
```

The field `layoutInDisplayCutoutMode` ( https://developer.android.com/reference/android/view/WindowManager.LayoutParams.html#layoutInDisplayCutoutMode ) indeed only exists since API version 28, which is android 9, but my device is android 8 and thus doesn't have this field (https://apilevels.com/).

I'll try to use `cargo quad-apk` again, to see if I can figure this out on my own and supply patches, but if something is obvious to you, please let me know

**Comment by not-fl3** [comment]
Its a bug :( 
https://github.com/not-fl3/miniquad/blob/master/java/MainActivity.java#L302

This is a commit to blame: https://github.com/not-fl3/miniquad/commit/9c41effcd9f1d04766a257b577dbf04dcf7e572c

Looks like its a runtime error, so some `if (Build.VERSION.SDK_INT >= N) {` should do it, I guess?
